export const FIREBASE_API_KEY = "AIzaSyBs53d4ywNoamorugt1_HxyonYVxS98cMo"
export const FIREBASE_AUTH_DOMAIN =   "earncaribbean.firebaseapp.com"
export const FIREBASE_DATABASE_URL = "https://earncaribbean.firebaseio.com"
export const FIREBASE_PROJECT_ID = "earncaribbean"
export const FIREBASE_STORAGE_BUCKET = ""
export const FIREBASE_MESSAGING_SENDER_ID = "343790026792"